import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
})
import { Manrope } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" 
    suppressContentEditableWarning>
      <body
        className={`${manrope.variable} antialiased`}
        suppressContentEditableWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
             {children}
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
